Error executing the script. Error: Traceback (most recent call last):
  File "F:\PYT\FLASK 2 auto\TAKE 50 with no spec char unicode\analyzer.py", line 418, in <module>
    lan_networks = [ipaddress.IPv4Network(network, strict=False) for network in lan_networks]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ipaddress.py", line 1512, in __init__
    self.network_address = IPv4Address(addr)
                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ipaddress.py", line 1315, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ipaddress.py", line 1207, in _ip_int_from_string
    raise AddressValueError("%s in %r" % (exc, ip_str)) from None
ipaddress.AddressValueError: At most 3 characters permitted in '1175' in '1175.103.46.95'
